-- Create core JPA tables used by the demo (accounts + transactions).
--
-- We keep DDL reasonably portable between H2 and Postgres.

CREATE TABLE IF NOT EXISTS accounts (
  account_number VARCHAR(20) PRIMARY KEY,
  account_name VARCHAR(100) NOT NULL,
  balance NUMERIC(19, 2) NOT NULL,
  status VARCHAR(20),
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP,
  version BIGINT NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS transactions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  transaction_id VARCHAR(50) NOT NULL,
  source_account VARCHAR(20) NOT NULL,
  dest_account VARCHAR(20) NOT NULL,
  amount NUMERIC(19, 2) NOT NULL,
  description VARCHAR(500),
  status VARCHAR(20),
  saga_state VARCHAR(30),
  error_message VARCHAR(1000),
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  completed_at TIMESTAMP,
  compensated_at TIMESTAMP
);

-- Idempotent unique constraint creation across both DBs is tricky;
-- prefer an index + constraint when supported.
CREATE UNIQUE INDEX IF NOT EXISTS ux_transactions_transaction_id ON transactions(transaction_id);
